name: ${project.name}
version: ${project.version}
author: totemo
authors: [totemo, bermudalocket]
description: ${project.description}
website: ${project.url}
main: nu.nerd.safecrystals.SafeCrystals
api-version: 1.15

depend: [WorldGuard]

permissions: {}

commands: {}

